     `:oyhhhyo:                        `:       
     `yMMMMMMMMMMNo                     .mN/      
    `mMMMMMMMMMMMMMh                    dMMMy     
   .yMMMMMMMMMMMMMMMds:`               `MMMMMo    
+hNMMMMMMMMMMMMMMMMMMMMMh/`             hMMMM+    
MMMMMMMMMMMMMMMMMMMMMMMMMMNs.           `sMMd     
/mMMMMMMMMMMMMMMMMMMMMMMMMMMMs`           .dm.    
  mMMMMMMMMMMMMMMMMMMMMMMMMMMMm.            sN-   
  -oyMMMMMMMMMMMMMMMMMMMMMMMMMMd             sN.  
    .MMMMMMMMMMMMMMMMMMMMMMMMMMM              hm` 
    `MMMMMMMMMMMMMMMMMMMMMMMMMM/              .Ms 
     NMMMMMMMMMMMMMMMMMMMMMMMMh`               sM-
     yMMMMMMMMMMMMMMMMMMMMMMMMMMy-             -My
      sMMMMMMMMMMMMMMMMMMMMMMMMMMMNy+:`         Mm
      yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds/     NM
      oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-  .Mm
      `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm  sMo
       .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysMd`
         /hmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm` 
             oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+ 
              sMMMMMMhdmMMMMMmdMMMMMMMMMMMMMMMMMM`
              -MMMMMh    ```  `sNMMMMMMMMMMMMMMh: 
          /ydmNMMMMMy   :+o++////smMMMMMMMMMMM:   
         /MMMMMMMMMM:  oMMMMMMMMMMMMMMMMMMMMMd    
         `syyyyyyyy:   :yhhhhhyssoo+++++oyhhhs    

Leo is bright and proud ruler. Leos are smart enough not to waste energy on useless projects.

 When they know they can easily sweep the floor with a broom, they will not take a toothbrush for this work.

Leos nature is to advise and manage others. They have a natural authority and they often do not even hide their own sense of superiority.

Every true Leo likes to hear how good he is. If you want to please him or win his favour, flatter him!

Leos like quality and they are willing to spend a lot of money for genuine luxury.
Leos usually love sport because they are naturally competitive and they like to show how successful they are.

They can sometimes be tactless and painfully honest. Leos would not like intentionally hurt anyone, but they are straightforward and do not like intrigues.

Leo is the one on which others rely. Try to offer him help, definitely he rejects it.
The Leo man is generally not a scrooge. He will take you to a better restaurant and bring a whole bouquet of flowers rather than one lonely rose.

The Leo woman is definitely not a silent housewife that would be sitting at your feet in the evening and eagerly listen to every your word. She is intelligent, capable and strong women.

Leos are not bitter. On the contrary, they are generous and know how to forgive.
